# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f8b21f9972d140af4d922176985daee077c1460b2ed95eae53c37d24099f6717729d47c2d94496dd1c6ef3ebc8d45b68597188511831d0ecae8619816d9dee3

test:
  secret_key_base: 7698b0caa100b4b8ac597b1fdb543a426d3fb11457b5757565372b4393c49aff26162e094833dc731111c670aa2c47dc6273e7b28652b9e2073129477dd1643d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
